{
 "title": "OOZIE WORKFLOW MONTHLY TREND",
 "description": "OOZIE WORKFLOW MONTHLY TREND",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "user_name",
    "label": "User Name",
    "query": "SELECT distinct username from oozie_jobs_killed_live;"
   },
   {
    "name": "workflow_name",
    "label": "Workflow Name",
    "query": "select distinct appname from oozie_jobs_monthly_trend"
   },
   {
    "name": "start_date",
    "label": "Start Date",
    "query": "select distinct to_char(startTime,'yyyy-mm-dd') from oozie_jobs_monthly_trend  order by 1 asc"
   },
   {
    "name": "end_date",
    "label": "End Date",
    "query": "select distinct to_char(startTime,'yyyy-mm-dd') from oozie_jobs_monthly_trend  order by 1 desc"
   },
   {
    "name": "monthly_order_by",
    "label": "Order By",
    "query": "select 'elaspedtime' as elaspedtime, 'date' as date ;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total No.of Workflows Successful",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) AS \"SUCCESS_COUNT\"\nFROM oozie_jobs_monthly_trend\nwhere to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') >= '$start_date'\nand to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') <= '$end_date'\nand status = 'SUCCEEDED' \nand username in ($user_name)\nand appname in ($workflow_name)",
     "target": "select metric",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Most Frequently Long Running Workflows > 3 Hours",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT appname,avg(elaspedtime) as avg_elasped_time from (\nSELECT\n  appname,\n  to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') as \"date\",\n  sum(EXTRACT(EPOCH FROM endtime - starttime)/3600) as elaspedtime\nFROM oozie_jobs_monthly_trend\nwhere to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') >= '$start_date'\nand to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') <= '$end_date'\nand status = 'SUCCEEDED' \nand username in ($user_name)\nand appname in ($workflow_name)\ngroup by appname,to_char(starttime + '4 hour'::interval,'yyyy-mm-dd')\n) src\nwhere elaspedtime > 3\ngroup by appname\norder by cast(avg(elaspedtime) as int) desc",
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Most Frequently Failed Workflows",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  appname,\n  count(appname) as count\nFROM oozie_jobs_monthly_trend\nwhere to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') >= '$start_date'\nand to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') <= '$end_date'\nand status = 'FAILED' \nand username in ($user_name)\nand appname in ($workflow_name)\ngroup by appname\norder by cast(count(1) as integer) desc",
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Most Frequently Killed Workflows",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  appname,\n  count(appname) as count\nFROM oozie_jobs_monthly_trend\nwhere to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') >= '$start_date'\nand to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') <= '$end_date'\nand status = 'KILLED' \nand username in ($user_name)\nand appname in ($workflow_name)\ngroup by appname\norder by cast(count(1) as integer) desc",
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "title": "Total No.of Workflows Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) AS \"SUCCESS_COUNT\"\nFROM oozie_jobs_monthly_trend\nwhere to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') >= '$start_date'\nand to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') <= '$end_date'\nand status = 'FAILED' \nand username in ($user_name)\nand appname in ($workflow_name)",
     "target": "select metric",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Total No.of Workflows Killed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) AS \"SUCCESS_COUNT\"\nFROM oozie_jobs_monthly_trend\nwhere to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') >= '$start_date'\nand to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') <= '$end_date'\nand status = 'KILLED' \nand username in ($user_name)\nand appname in ($workflow_name)",
     "target": "select metric",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Workflow Trend By Execution Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (startTime + '4 hour'::interval) as \"time\",\n  to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') as \"date\",\n  sum(EXTRACT(EPOCH FROM endtime - starttime)/3600) as elaspedtime\nFROM oozie_jobs_monthly_trend\nwhere to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') >= '$start_date'\nand to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') <= '$end_date'\nand status = 'SUCCEEDED' \nand username in ($user_name)\nand appname in ($workflow_name)\ngroup by (startTime + '4 hour'::interval)\norder by $monthly_order_by desc",
     "target": "select metric",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Workflow Trend By Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  starttime as \"time\",\n  to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') as date,\n  count(1) AS \"SUCCESS_COUNT\"\nFROM oozie_jobs_monthly_trend\nwhere to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') >= '$start_date'\nand to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') <= '$end_date'\nand status = 'SUCCEEDED' \nand username in ($user_name)\nand appname in ($workflow_name)\ngroup by starttime\norder by $monthly_order_by desc",
     "target": "select metric",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Monthly Killed & Failed Workflows",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT AppName,StartTime,EndTime,Status,UserName,'http://dolinux759.hq.emirates.com:8888/oozie/list_oozie_workflow/' || id as workflowURL\nFROM oozie_jobs_monthly_trend\nwhere to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') >= '$start_date'\nand to_char(starttime + '4 hour'::interval,'yyyy-mm-dd') <= '$end_date'\nand status in ('FAILED','KILLED') \nand username in ($user_name)\nand appname in ($workflow_name)\norder by starttime desc",
     "target": "select metric",
     "type": "table"
    }
   ]
  }
 ]
}